name: CI and Native Build for GraalVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up GraalVM 23
      - name: Set up GraalVM 23
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'   # Use GraalVM distribution
          java-version: '23'        # Set Java version to 23

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test with Maven
      - name: Build and run tests
        run: mvn clean verify

      # Step 6: Build Native Image
      - name: Build Native Image
        run: mvn package -Pnative -DskipTests=true

      # Step 7: Upload Native Image Artifact
      - name: Upload native image as build artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-image
          path: target/*-runner